version: '3.8'

volumes:
  pg_data:
    driver: local

services:
  db:
    image: library/postgres:16
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  dataset-service:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    command: uvicorn apps.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
